/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "brick_game/tetris/test/test_s21_tetris.check" instead.
 */

#include <check.h>

#line 1 "brick_game/tetris/test/test_s21_tetris.check"
# include "test_s21_tetris.h"


START_TEST(userInput_0)
{
#line 6
UserAction_t action = Start;
bool hold = 0;
userInput(action, hold);
UserAction_t *input = get_instance_input_to_fsm();
ck_assert_int_eq(*input, Start);

}
END_TEST

START_TEST(userInput_1)
{
#line 13
UserAction_t action = Pause;
bool hold = 0;
userInput(action, hold);
UserAction_t *input = get_instance_input_to_fsm();
ck_assert_int_eq(*input, Pause);

}
END_TEST

START_TEST(userInput_2)
{
#line 20
UserAction_t action = Terminate;
bool hold = 0;
userInput(action, hold);
UserAction_t *input = get_instance_input_to_fsm();
ck_assert_int_eq(*input, Terminate);

}
END_TEST

START_TEST(userInput_3)
{
#line 27
UserAction_t action = Left;
bool hold = 0;
userInput(action, hold);
UserAction_t *input = get_instance_input_to_fsm();
ck_assert_int_eq(*input, Left);

}
END_TEST

START_TEST(userInput_4)
{
#line 34
UserAction_t action = Right;
bool hold = 0;
userInput(action, hold);
UserAction_t *input = get_instance_input_to_fsm();
ck_assert_int_eq(*input, Right);

}
END_TEST

START_TEST(userInput_5)
{
#line 41
UserAction_t action = Up;
bool hold = 0;
userInput(action, hold);
UserAction_t *input = get_instance_input_to_fsm();
ck_assert_int_eq(*input, Up);

}
END_TEST

START_TEST(userInput_6)
{
#line 48
UserAction_t action = Down;
bool hold = 0;
userInput(action, hold);
UserAction_t *input = get_instance_input_to_fsm();
ck_assert_int_eq(*input, Down);

}
END_TEST

START_TEST(userInput_7)
{
#line 55
UserAction_t action = Action;
bool hold = 0;
userInput(action, hold);
UserAction_t *input = get_instance_input_to_fsm();
ck_assert_int_eq(*input, Action);

}
END_TEST

START_TEST(fsm_0)
{
#line 62
UserAction_t action = Start;
bool hold = 0;
userInput(action, hold);
finite_state_machine *fsm = get_instance_fsm();
ck_assert_int_eq(*fsm, spawn);

}
END_TEST

START_TEST(fsm_1)
{
#line 69
UserAction_t action = Action;
bool hold = 0;
userInput(action, hold);
finite_state_machine *fsm = get_instance_fsm();
ck_assert_int_eq(*fsm, start);

}
END_TEST

START_TEST(field_0)
{
#line 76
UserAction_t action = Start;
bool hold = 0;
userInput(action, hold);
InsideGameInfo_t *tetris = get_instance_tetris();
ck_assert_ptr_ne(tetris->field, S21_NULL);
ck_assert_ptr_ne(tetris->next, S21_NULL);

}
END_TEST

START_TEST(tetris_act_0)
{
#line 84
bool hold = 0;
userInput(Start, hold);
for (int i = 0; i < 80; i++) {
    userInput(Down, hold);
}
GameInfo_t tetris = updateCurrentState();
ck_assert_ptr_ne(tetris.field, S21_NULL);
ck_assert_ptr_eq(tetris.next, S21_NULL);

}
END_TEST

START_TEST(tetris_act_1)
{
#line 94
bool hold = 0;
char* action = "6066066766446466666666666666766366666666666666666676676336633636666666666666676766";
for (int i = 0; i < (int)strlen(action); i++) {
    userInput((int)(action[i]) - 48, hold);
}
GameInfo_t tetris = updateCurrentState();
ck_assert_ptr_ne(tetris.field, S21_NULL);
ck_assert_ptr_ne(tetris.next, S21_NULL);
ck_assert_int_eq(tetris.score, 100);

}
END_TEST

START_TEST(tetris_act_2)
{
#line 105
bool hold = 0;
char* action = "2";
for (int i = 0; i < (int)strlen(action); i++) {
    userInput((int)(action[i]) - 48, hold);
}
GameInfo_t tetris = updateCurrentState();
ck_assert_ptr_eq(tetris.field, S21_NULL);
ck_assert_ptr_eq(tetris.next, S21_NULL);
ck_assert_int_eq(tetris.score, 0);

}
END_TEST

START_TEST(tetris_act_3)
{
#line 116
bool hold = 0;
char* action = "606664646664664676633676646466666766666666366666666666676736633636636666666666666667676762";
for (int i = 0; i < (int)strlen(action); i++) {
    userInput((int)(action[i]) - 48, hold);
}
GameInfo_t tetris = updateCurrentState();
ck_assert_ptr_eq(tetris.field, S21_NULL);
ck_assert_ptr_eq(tetris.next, S21_NULL);
ck_assert_int_eq(tetris.score, 100);

}
END_TEST

START_TEST(tetris_act_4)
{
#line 127
bool hold = 0;
char* action = "60666666666166661666662";
for (int i = 0; i < (int)strlen(action); i++) {
    userInput((int)(action[i]) - 48, hold);
}
GameInfo_t tetris = updateCurrentState();
ck_assert_ptr_eq(tetris.field, S21_NULL);
ck_assert_ptr_eq(tetris.next, S21_NULL);

}
END_TEST

START_TEST(tetris_act_5)
{
#line 137
bool hold = 0;
char* action = "02";
for (int i = 0; i < (int)strlen(action); i++) {
    userInput((int)(action[i]) - 48, hold);
}
GameInfo_t tetris = updateCurrentState();
ck_assert_ptr_eq(tetris.field, S21_NULL);
ck_assert_ptr_eq(tetris.next, S21_NULL);
ck_assert_int_eq(tetris.score, 0);

}
END_TEST

START_TEST(tetris_act_6)
{
#line 148
bool hold = 0;
char* action = "6606336636336676336663466446662";
for (int i = 0; i <= (int)strlen(action); i++) {
    userInput((int)(action[i]) - 48, hold);
}
GameInfo_t tetris = updateCurrentState();
ck_assert_ptr_eq(tetris.field, S21_NULL);
ck_assert_ptr_eq(tetris.next, S21_NULL);
ck_assert_int_eq(tetris.score, 0);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("tetris");
    TCase *tc1_1 = tcase_create("tetris");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, userInput_0);
    tcase_add_test(tc1_1, userInput_1);
    tcase_add_test(tc1_1, userInput_2);
    tcase_add_test(tc1_1, userInput_3);
    tcase_add_test(tc1_1, userInput_4);
    tcase_add_test(tc1_1, userInput_5);
    tcase_add_test(tc1_1, userInput_6);
    tcase_add_test(tc1_1, userInput_7);
    tcase_add_test(tc1_1, fsm_0);
    tcase_add_test(tc1_1, fsm_1);
    tcase_add_test(tc1_1, field_0);
    tcase_add_test(tc1_1, tetris_act_0);
    tcase_add_test(tc1_1, tetris_act_1);
    tcase_add_test(tc1_1, tetris_act_2);
    tcase_add_test(tc1_1, tetris_act_3);
    tcase_add_test(tc1_1, tetris_act_4);
    tcase_add_test(tc1_1, tetris_act_5);
    tcase_add_test(tc1_1, tetris_act_6);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
